### ISSUE TITLE
VTR300 is not answering

### ISSUE THREAD

**Issue by ChristophDramski** [Ztaeyn/HomeAssistant-VTR-Modbus#21]
Hello @Ztaeyn,

sorry that I am disturbing you.
I have paste your yaml file and fitt the ip adress as you said. I am able to send the data to VTR300, but I dont receiving a data from it.
I am using as @cmragnar a Waveshare https://www.waveshare.com/w/upload/8/86/RS485-TO-ETH-B-user-manual-en-v1.1.pdf to manage the data. I am sitting since days and I am little bit frustrated. I dont have IAM and Save Touch panel. I am stearing my VTR with a help of Save Light. 
Thank you for your help in advice.

Best regards,
Chris

**Comment by cmragnar** [comment]
Hi,
Think your device don't support modbus, mening you cant send.
If you are using this one: https://www.waveshare.com/rs485-to-eth.htm

This one is modbus: https://www.waveshare.com/RS232-485-TO-ETH.htm

**Comment by ChristophDramski** [comment]
Hi @cmragnar, 

nice to hear from you :-)
I am using this one: https://www.waveshare.com/rs485-to-eth-b.htm
My settings for them: 
![1704469526828](https://github.com/Ztaeyn/HomeAssistant-VTR-Modbus/assets/140876499/5e433360-c8fc-4f1f-ba2d-0c99bc949d2d)

So I can choose a Modbus TCP Protocol. In yaml file I have following:
![1704469760343](https://github.com/Ztaeyn/HomeAssistant-VTR-Modbus/assets/140876499/c1dac520-3ea8-49eb-9996-3a9a297142e1)

I have also checked signals with oscyloscope. I am seeing I have sending something... but in HA I dont see any result :-(

**Comment by Ztaeyn** [comment]
Hi, I am myself using an "ELFIN-EW11A-485" (to wifi), where my basic settings differ with higher baud rate at 115.200, even though the manual (linked below) says to use 19.200. I can't communicate at all with that setting.



https://shop.systemair.com/upload/assets/MODBUS_FOR_RESIDENTIAL_D24810_USER_MANUAL_EN__A007_.PDF

**Comment by ChristophDramski** [comment]
Thanks for your answers, @Ztaeyn. I have seen you are wrote in your yaml rtuovertcp, but @cmragnar use Type: TCP. Can I see your settings on ELFIN Side?

How can I see in HA that data from VTR is coming?

Thanks a lot for your help and support :-)

**Comment by Ztaeyn** [comment]
> Thanks for your answers, @Ztaeyn. I have seen you are wrote in your yaml rtuovertcp, but @cmragnar use Type: TCP. Can I see your settings on ELFIN Side?
> 
> How can I see in HA that data from VTR is coming?
> 
> Thanks a lot for your help and support :-)

I actually use "TCP" , but from the phone app I merged in another guys changes that use rtuovertp , did not bother changing it as I anyhow secure my own setting :)

First off I would confirm in the controller web interface if it is receiving data, any value above 0, 
then check a few sensors with typically fluctuating data like  sensor.vsr300_heat_recovery, 

![image](https://github.com/Ztaeyn/HomeAssistant-VTR-Modbus/assets/58105460/33ded33b-4bc0-4999-b951-bf6ebcf38785)
![image](https://github.com/Ztaeyn/HomeAssistant-VTR-Modbus/assets/58105460/5c529243-34e2-4403-8156-a41d44618130)
(huh, says uart route in the last picture)

**Comment by ChristophDramski** [comment]
Thanks a lot for pictures. Hmm my settings seems similar. I am checking the communication on HA side with vsr300_exhaust_air_max_sp, but still seeing not available :-( On Waveshare I am seeing TX that I am sending something but RX is still 0. 

I hope that I must not activate or change something on VTR side. Did you activate modbus option (or something Like that) on VTR side?

Thanks a lot for your help and sorry that I am disturbing you :-(

**Comment by Ztaeyn** [comment]
Not disturbing me at all :) 

I think you have to check the vtr settings for Modbus , match up the settings / enable etc.

https://community.home-assistant.io/t/systemair-savecare-ventilation-unit/229653/91

**Comment by ChristophDramski** [comment]
The problem is I have no possibility to check modbus on VTR side. I have only very simple touch panel: 
[
![1704490351190](https://github.com/Ztaeyn/HomeAssistant-VTR-Modbus/assets/140876499/f0cf26af-bae0-4310-b497-6e8f1880328e)
](url) 

:-(

**Comment by ChristophDramski** [comment]
Hello @Ztaeyn , Hello @cmragnar ,

I have wrote the manufacturer. The issue was the baud rate. When you have a VTR 300 BL Ver.A you should work with 1200 Bd (Default-Setting from Manufacturer). Then work everything :-) 

@Ztaeyn : I can read a data but I cant set a register. For example: I want to turn on "High Speed", but nothing changed on the side of VTR. I have seen in Entities, that some VTR-Entities are "secured" and cant be written :-( Do you have a Idea?

Best regards,
Chris

**Comment by Ztaeyn** [comment]
I'm really sorry to say I do not know.

**Comment by ChristophDramski** [comment]
Hello @Ztaeyn,

It is working! Thanks for your help :-)
I have only 3 questions:

- Do you know meaning of Alarm A, B nad C? 
- How can I set a Filter alarm period?
- I dont see a action after push the button for "Stopp" and "Auto".

Can you help me with this points above?

Best regards, 
Christoph

**Comment by Ztaeyn** [comment]
Hi @ChristophDramski .
Regarding the alarms,. I had to google. I 've wondered myself but forgotten all about it- All i learned was that class C is repetive alarm.


ref: https://shop.systemair.com/upload/assets/QUICKGUIDE_ACCESS_SW_4_0-1-04_TO_4_6-1-00_151671_EN_A011.PDF?8182a401

Different alarm levels
Class A alarm
Needs to be acknowledged
Class B alarm
Needs to be acknowledged
Class C alarm
Returns when the cause of the alarm disappear

For Stop , It looks like it does not work (never tried it, copied it in since it was in GMTravis node red code.
Auto works for me, If I have it in manual mode, it changes to auto.

For setting filter alarm, that's missing in the code. I tried to add it in now, but I am dead tired, did something wrong and had to revert changes. I will look back into it when I get time off, better call it a day for now since the kid will by default wake me up in 4-5 hours from now ..

**Comment by Ztaeyn** [comment]
@ChristophDramski good news!
I have added the possibility to set the filter period, and it seems to be working. I had not updated my systems with changes from other users, so I'm trying to test it with the latest configuration as well.

**Comment by ChristophDramski** [comment]
@Ztaeyn nice! Thank you very much for that. Do you want to push this changes into the branch of your project? I will be really gratefull for that :-) best regards

**Comment by Ztaeyn** [comment]
Just did! I edited my previous comment as you posted 😅

**Comment by ChristophDramski** [comment]
Hahaha 😂👍 thanks a lot for your help, I am really Happy about it. I will test it tomorrow and let you know about results.😊 Now I must check what is going on with auto mode. It is little bit weird for me

**Comment by Ztaeyn** [comment]
Hi, how did it go?

**Comment by ChristophDramski** [comment]
Hi @Ztaeyn, sorry for my late anwser. I was really busy the last time. I have changed filters in my VTR300 and set the new time period with a help of your code. Everythin is working fine! Thanks a lot for your help, support and work! Best regards, Christoph

**Comment by gaustabl** [comment]
Hello.
Hope somebody can help.....I have copied a pated the yaml files, but it will not connect tom my vtr300. I am using the save connect 2 module, connected via wifi.  When i search the log for modes i get 2 errors:
Logger: pymodbus.logging
Kilde: components/modbus/modbus.py:325
Førs oppstått: 00:25:05 (1 hendelser)
Sist logget: 00:25:05

Failed to connect [Errno 111] Connect call failed ('192.168.0.42', 8989)

and

Logger: homeassistant.components.modbus.modbus
Kilde: components/modbus/modbus.py:318
integrasjon: Modbus (dokumentasjon, problemer)
Førs oppstått: 00:25:12 (1 hendelser)
Sist logget: 00:25:12

Pymodbus: VSR300: Error: device: 1 address: 2000 -> Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.0.42:8989]

So it seems it does not connect, so i wonder if it could be wrong port no. (have also tried 502), or anything else??? 

Any help is much appreciated:)
best regards Lars

**Comment by gaustabl** [comment]
Update; found a program to scan for ports on the saveconnect, an it onl found port 80. So i give up for now😢

**Comment by gaustabl** [comment]
Update 2. i have odered a modbus to wifi adapter, and while waiting i am tryng to make verything ready. Can somebody please tell me where to put the code in the controlpanel_ information.txt file? 

Best regards Lars

**Comment by Ikkeno** [comment]
Maybe this is common knowledge, but to me it wasn't. Slave address 0 is not for reading to my knowledge. If your unit is still on default values the first thing to do is to change slave address to something other than 0. Then you will be able to read values from your unit also. I've got the Light control panel and used QModMaster to change the slave address, and now i got at connection in HA.
